#!/usr/bin/env node

const chalk = require('chalk');
const { JestExRunner } = require('jest-ex');

new JestExRunner('./.jestrc.json', {
  addTransformer: true,
  addStubs: true,
  cache: false,
})
.run()
.then(() => chalk.green('Yay! all the unit tests passed!'))
.catch(() => chalk.red('Damn... something went wrong with the unit tests'));
